;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
cd-dev=cd "C:/Projects"
root=cd "C:\Projects\clp"
nt=npm run test
ns=npm start
go=git checkout $*
gs=git status
gc=git commit -am $*
ga=git add .
push=git push $*
pushOrigin=node "C:/Projects/docs/scripts/push-origin.js" $*
pull=git pull $*
pulldev=git pull origin dev
removeUntracked=git clean -df
removeUnstaged=git checkout -- .
helpme=cat "C:\Users\plabus\Desktop\Root Folder\cmder\config\user_aliases.cmd"
open-aliases=notepad "C:\Users\plabus\Desktop\Root Folder\cmder\config\user_aliases.cmd"
renameCurrentBranch=git branch -m $*
clearIdeaGitCache=git rm --cached -r .idea
branches=git branch -a --sort=-committerdate | tail -n 10
test=node "C:\Projects\docs\scripts\testing-files.js" $* | xargs ng test --watch