PATH_TO_MAZE_IMAGE_OUTPUT = 'C:/Projects/docs/algorithms/maze/maze_paths/*'

MAX_MOVES = 40
GENERATIONS = 2000
POPULATION_SIZE = 50
MUTATIONS = 10

# FITNESS
SOLUTION_FOUND_FITNESS_VALUE = 10000
DEAD_END_FITNESS_VALUE = -10000
NEGATIVE_FINISH_MULTIPLIER = 5  # 25
STEPS_MULTIPLIER = 25

PATH: int = 0
WALL: int = 1
START: int = 2
END: int = 3
VISIT: int = 4
DEAD_END: int = 5
